import { env } from "../../config/env";

export const MATCHING_CONSTANTS = {
  // Candidate limits
  MAX_CANDIDATES: env.MATCHING_MAX_CANDIDATES || 50,
  MAX_ROUTE_CALCULATIONS: env.MATCHING_MAX_ROUTE_CALCULATIONS || 10,
  DEFAULT_RESULTS_LIMIT: env.DISCOVERY_MAX_RESULTS || 20,
  MAX_RESULTS_LIMIT: 50,

  // Distance & Proximity Defaults (in meters)
  DEFAULT_PICKUP_RADIUS_METERS: env.MATCHING_PICKUP_RADIUS_METERS || 1500,
  MAX_ALLOWED_PICKUP_RADIUS_METERS: 5000,
  DEFAULT_DESTINATION_RADIUS_METERS: env.MATCHING_DESTINATION_RADIUS_METERS || 3000,
  MAX_ALLOWED_DESTINATION_RADIUS_METERS: 10000,
  MAX_DETOUR_METERS: env.MATCHING_MAX_DETOUR_METERS || 4000,

  // Direction thresholds (in degrees)
  SAME_DIRECTION_THRESHOLD_DEGREES: env.MATCHING_DIRECTION_SAME_THRESHOLD_DEGREES || 45,
  OPPOSITE_DIRECTION_THRESHOLD_DEGREES: env.MATCHING_DIRECTION_OPPOSITE_THRESHOLD_DEGREES || 135,

  // Progress tolerance
  ROUTE_PROGRESS_TOLERANCE: 0.05,

  // Classification Thresholds
  HIGH_SCORE_THRESHOLD: 0.70,
  MEDIUM_SCORE_THRESHOLD: 0.45,

  // Scoring Weights
  WEIGHTS: {
    PICKUP: env.MATCHING_PICKUP_WEIGHT || 0.30,
    DESTINATION: env.MATCHING_DESTINATION_WEIGHT || 0.25,
    DIRECTION: env.MATCHING_DIRECTION_WEIGHT || 0.15,
    PROGRESS: env.MATCHING_PROGRESS_WEIGHT || 0.15,
    DETOUR: env.MATCHING_DETOUR_WEIGHT || 0.10,
    FRESHNESS: env.MATCHING_FRESHNESS_WEIGHT || 0.05,
  },

  // Session TTL
  SESSION_TTL_MINUTES: env.DISCOVERY_SESSION_TTL_MINUTES || 15,
} as const;
